// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: events/v1/archive.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ArchiveRecord is one Category I record in flight between the service
// that produced it and the archive that stores it.
//
// IT CARRIES THE CANONICAL BYTES, NOT THE MESSAGE. That is the whole
// point of this envelope. Records are content-addressed by a BLAKE3
// hash over their canonical encoding, and
// `proto.MarshalOptions{Deterministic: true}` explicitly does NOT
// promise the same bytes across builds or protobuf versions. A consumer
// that re-marshalled the message to recompute the hash could therefore
// disagree with the producer about a record's identity — silently
// breaking idempotency across exactly the version skew a deployed
// system spends its life in.
//
// So the producer canonicalizes once, and everything downstream treats
// `canonical_payload` as opaque bytes it may verify but must never
// regenerate.
type ArchiveRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The exact canonical encoding of the record. Opaque here.
	CanonicalPayload []byte `protobuf:"bytes,1,opt,name=canonical_payload,json=canonicalPayload,proto3" json:"canonical_payload,omitempty"`
	// Lowercase hex BLAKE3 over canonical_payload. The consumer verifies
	// rather than trusts: a mismatch means the bytes did not survive the
	// trip, and committing them would poison a content-addressed store.
	EventHash string `protobuf:"bytes,2,opt,name=event_hash,json=eventHash,proto3" json:"event_hash,omitempty"`
	// The record's own notion of when it happened, Unix nanoseconds —
	// distinct from the commit timestamp, which the archive sets on
	// arrival. The gap between the two is itself information.
	EventTime int64 `protobuf:"varint,3,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	// Fully-qualified protobuf name of the message inside
	// canonical_payload, e.g. "ghosttrace.events.v1.Evaluation".
	MessageType string `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// The tenant this record belongs to. Also the last token of the
	// subject it travels on, so a consumer can be scoped without
	// decoding.
	Tenant        string `protobuf:"bytes,5,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRecord) Reset() {
	*x = ArchiveRecord{}
	mi := &file_events_v1_archive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRecord) ProtoMessage() {}

func (x *ArchiveRecord) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_archive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRecord.ProtoReflect.Descriptor instead.
func (*ArchiveRecord) Descriptor() ([]byte, []int) {
	return file_events_v1_archive_proto_rawDescGZIP(), []int{0}
}

func (x *ArchiveRecord) GetCanonicalPayload() []byte {
	if x != nil {
		return x.CanonicalPayload
	}
	return nil
}

func (x *ArchiveRecord) GetEventHash() string {
	if x != nil {
		return x.EventHash
	}
	return ""
}

func (x *ArchiveRecord) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *ArchiveRecord) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ArchiveRecord) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

var File_events_v1_archive_proto protoreflect.FileDescriptor

var file_events_v1_archive_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x67, 0x68, 0x6f, 0x73, 0x74,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22,
	0xb5, 0x01, 0x0a, 0x0d, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x63, 0x61,
	0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a,
	0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46, 0x61, 0x62, 0x69, 0x6f, 0x43, 0x61, 0x66, 0x66, 0x61,
	0x72, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2d, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_v1_archive_proto_rawDescOnce sync.Once
	file_events_v1_archive_proto_rawDescData = file_events_v1_archive_proto_rawDesc
)

func file_events_v1_archive_proto_rawDescGZIP() []byte {
	file_events_v1_archive_proto_rawDescOnce.Do(func() {
		file_events_v1_archive_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_v1_archive_proto_rawDescData)
	})
	return file_events_v1_archive_proto_rawDescData
}

var file_events_v1_archive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_v1_archive_proto_goTypes = []any{
	(*ArchiveRecord)(nil), // 0: ghosttrace.events.v1.ArchiveRecord
}
var file_events_v1_archive_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_v1_archive_proto_init() }
func file_events_v1_archive_proto_init() {
	if File_events_v1_archive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_v1_archive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_archive_proto_goTypes,
		DependencyIndexes: file_events_v1_archive_proto_depIdxs,
		MessageInfos:      file_events_v1_archive_proto_msgTypes,
	}.Build()
	File_events_v1_archive_proto = out.File
	file_events_v1_archive_proto_rawDesc = nil
	file_events_v1_archive_proto_goTypes = nil
	file_events_v1_archive_proto_depIdxs = nil
}
