// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: events/v1/outcome.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outcome is what actually happened after a decision (§3
// POST /v1/outcomes).
//
// Without this endpoint there are no labels; without labels there is no
// calibration; without calibration the false-positive rate is a guess.
// It is the difference between a detector and a platform.
//
// Outcomes arrive late — a chargeback can land weeks after the decision,
// long past the 7-day raw-event retention — which is why `evaluation_id`
// must stay durable well beyond the events, and why the Evaluation
// record carries its own feature state.
//
// An outcome is a Category I observation: an immutable historical fact
// reported by the application. It is never revised. A later, better
// outcome for the same evaluation is a NEW record, and the join is
// resolved by reading time order rather than by mutation.
type Outcome struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The decision this outcome is about.
	EvaluationId string `protobuf:"bytes,2,opt,name=evaluation_id,json=evaluationId,proto3" json:"evaluation_id,omitempty"`
	// One of: login_success | login_failure | challenge_passed |
	// challenge_failed | fraud_confirmed | user_appealed | abandoned.
	Outcome string `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// When the application observed it, Unix nanoseconds. Application
	// clock — trusted no more than any other caller-supplied value, but
	// recorded as claimed.
	ObservedAt int64 `protobuf:"varint,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// Server wall-clock nanoseconds at acceptance. Server-observed, so
	// the trustworthy half of the pair; the gap between the two is itself
	// worth watching.
	RecordedAt    int64 `protobuf:"varint,5,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_events_v1_outcome_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_outcome_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_events_v1_outcome_proto_rawDescGZIP(), []int{0}
}

func (x *Outcome) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Outcome) GetEvaluationId() string {
	if x != nil {
		return x.EvaluationId
	}
	return ""
}

func (x *Outcome) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *Outcome) GetObservedAt() int64 {
	if x != nil {
		return x.ObservedAt
	}
	return 0
}

func (x *Outcome) GetRecordedAt() int64 {
	if x != nil {
		return x.RecordedAt
	}
	return 0
}

var File_events_v1_outcome_proto protoreflect.FileDescriptor

var file_events_v1_outcome_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x75, 0x74, 0x63,
	0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x67, 0x68, 0x6f, 0x73, 0x74,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22,
	0xa7, 0x01, 0x0a, 0x07, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x64, 0x41, 0x74, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46, 0x61, 0x62, 0x69, 0x6f, 0x43, 0x61, 0x66,
	0x66, 0x61, 0x72, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2d, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_v1_outcome_proto_rawDescOnce sync.Once
	file_events_v1_outcome_proto_rawDescData = file_events_v1_outcome_proto_rawDesc
)

func file_events_v1_outcome_proto_rawDescGZIP() []byte {
	file_events_v1_outcome_proto_rawDescOnce.Do(func() {
		file_events_v1_outcome_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_v1_outcome_proto_rawDescData)
	})
	return file_events_v1_outcome_proto_rawDescData
}

var file_events_v1_outcome_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_v1_outcome_proto_goTypes = []any{
	(*Outcome)(nil), // 0: ghosttrace.events.v1.Outcome
}
var file_events_v1_outcome_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_v1_outcome_proto_init() }
func file_events_v1_outcome_proto_init() {
	if File_events_v1_outcome_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_v1_outcome_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_outcome_proto_goTypes,
		DependencyIndexes: file_events_v1_outcome_proto_depIdxs,
		MessageInfos:      file_events_v1_outcome_proto_msgTypes,
	}.Build()
	File_events_v1_outcome_proto = out.File
	file_events_v1_outcome_proto_rawDesc = nil
	file_events_v1_outcome_proto_goTypes = nil
	file_events_v1_outcome_proto_depIdxs = nil
}
