// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: events/v1/session.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionStart records the issuance of a session token (§3
// POST /v1/sessions).
//
// The client properties here are normalization inputs, not identity.
// The admission test per contract §0: does this property change how
// behaviour should be interpreted? A 400px viewport produces different
// scroll dynamics than a 1440px one, and a trackpad produces a
// structurally different pointer trace than a mouse — comparing them
// without normalizing measures the input device, not the operator.
//
// Nothing here may be used to tell one browser from another. Canvas,
// WebGL, font enumeration and audio fingerprinting are out of scope and
// contradict the thesis (§0).
type SessionStart struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TenantId  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Server wall-clock nanoseconds at issuance.
	StartedAt int64  `protobuf:"varint,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	PagePath  string `protobuf:"bytes,4,opt,name=page_path,json=pagePath,proto3" json:"page_path,omitempty"`
	// CSS pointer media feature: "fine" | "coarse" | "none".
	PointerType string `protobuf:"bytes,5,opt,name=pointer_type,json=pointerType,proto3" json:"pointer_type,omitempty"`
	Touch       bool   `protobuf:"varint,6,opt,name=touch,proto3" json:"touch,omitempty"`
	ViewportW   uint32 `protobuf:"varint,7,opt,name=viewport_w,json=viewportW,proto3" json:"viewport_w,omitempty"`
	ViewportH   uint32 `protobuf:"varint,8,opt,name=viewport_h,json=viewportH,proto3" json:"viewport_h,omitempty"`
	// Minutes offset from UTC. Coarse; a normalization input for
	// time-of-day effects, not a locator.
	TzOffsetMin int32 `protobuf:"varint,9,opt,name=tz_offset_min,json=tzOffsetMin,proto3" json:"tz_offset_min,omitempty"`
	// prefers-reduced-motion. Load-bearing for fairness: users with this
	// set are among those most at risk of a false positive, so the signal
	// must be available to the scorer rather than silently absent.
	ReducedMotion bool `protobuf:"varint,10,opt,name=reduced_motion,json=reducedMotion,proto3" json:"reduced_motion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStart) Reset() {
	*x = SessionStart{}
	mi := &file_events_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStart) ProtoMessage() {}

func (x *SessionStart) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStart.ProtoReflect.Descriptor instead.
func (*SessionStart) Descriptor() ([]byte, []int) {
	return file_events_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *SessionStart) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SessionStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStart) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *SessionStart) GetPagePath() string {
	if x != nil {
		return x.PagePath
	}
	return ""
}

func (x *SessionStart) GetPointerType() string {
	if x != nil {
		return x.PointerType
	}
	return ""
}

func (x *SessionStart) GetTouch() bool {
	if x != nil {
		return x.Touch
	}
	return false
}

func (x *SessionStart) GetViewportW() uint32 {
	if x != nil {
		return x.ViewportW
	}
	return 0
}

func (x *SessionStart) GetViewportH() uint32 {
	if x != nil {
		return x.ViewportH
	}
	return 0
}

func (x *SessionStart) GetTzOffsetMin() int32 {
	if x != nil {
		return x.TzOffsetMin
	}
	return 0
}

func (x *SessionStart) GetReducedMotion() bool {
	if x != nil {
		return x.ReducedMotion
	}
	return false
}

var File_events_v1_session_proto protoreflect.FileDescriptor

var file_events_v1_session_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x67, 0x68, 0x6f, 0x73, 0x74,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22,
	0xc8, 0x02, 0x0a, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x75, 0x63, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x74, 0x6f, 0x75, 0x63,
	0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x65, 0x77, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x77, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x69, 0x65, 0x77, 0x70, 0x6f, 0x72, 0x74, 0x57,
	0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x65, 0x77, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x68, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x69, 0x65, 0x77, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x12,
	0x22, 0x0a, 0x0d, 0x74, 0x7a, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f, 0x6d, 0x69, 0x6e,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x7a, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x4d, 0x69, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64, 0x5f, 0x6d,
	0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x72, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x64, 0x4d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46, 0x61, 0x62, 0x69, 0x6f, 0x43, 0x61,
	0x66, 0x66, 0x61, 0x72, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2d, 0x74,
	0x72, 0x61, 0x63, 0x65, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_v1_session_proto_rawDescOnce sync.Once
	file_events_v1_session_proto_rawDescData = file_events_v1_session_proto_rawDesc
)

func file_events_v1_session_proto_rawDescGZIP() []byte {
	file_events_v1_session_proto_rawDescOnce.Do(func() {
		file_events_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_v1_session_proto_rawDescData)
	})
	return file_events_v1_session_proto_rawDescData
}

var file_events_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_v1_session_proto_goTypes = []any{
	(*SessionStart)(nil), // 0: ghosttrace.events.v1.SessionStart
}
var file_events_v1_session_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_v1_session_proto_init() }
func file_events_v1_session_proto_init() {
	if File_events_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_v1_session_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_session_proto_goTypes,
		DependencyIndexes: file_events_v1_session_proto_depIdxs,
		MessageInfos:      file_events_v1_session_proto_msgTypes,
	}.Build()
	File_events_v1_session_proto = out.File
	file_events_v1_session_proto_rawDesc = nil
	file_events_v1_session_proto_goTypes = nil
	file_events_v1_session_proto_depIdxs = nil
}
