// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: events/v1/snapshot.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionSnapshot is everything a decision needs about a session,
// serialized so the decision can be made by a process that did not
// observe it.
//
// It carries FEATURE STATE, never raw events. That is what makes the
// split affordable: the decision path already reduces a session to
// nineteen numbers before scoring it, so the snapshot is small and
// bounded no matter how long the session runs — and it is also what
// keeps the collector the single writer, since nothing downstream needs
// the event history to reproduce a judgement.
//
// The collector writes one on every telemetry batch; the decision
// engine reads the latest. That is the same semantics the monolith
// already has — "decide on the most recent state" — expressed across a
// process boundary instead of a mutex.
type SessionSnapshot struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TenantId  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Milliseconds from session start to the most recent event. This is
	// the evidence window a decision reports, and it is a property of the
	// session rather than of the snapshot.
	LastEventMs uint32 `protobuf:"varint,3,opt,name=last_event_ms,json=lastEventMs,proto3" json:"last_event_ms,omitempty"`
	// Unix nanoseconds when the collector produced this snapshot.
	// Distinct from last_event_ms: the gap between them is how stale the
	// reader's view is, which is the cost of the split made visible.
	WrittenAt int64 `protobuf:"varint,4,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	// The nineteen numbers a judgement is computed from. Reusing
	// FeatureState rather than declaring a second shape is deliberate:
	// the archived evaluation already carries this message, and two
	// definitions of "what the detector looked at" would be free to
	// drift.
	Features      *FeatureState `protobuf:"bytes,5,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSnapshot) Reset() {
	*x = SessionSnapshot{}
	mi := &file_events_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSnapshot) ProtoMessage() {}

func (x *SessionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSnapshot.ProtoReflect.Descriptor instead.
func (*SessionSnapshot) Descriptor() ([]byte, []int) {
	return file_events_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SessionSnapshot) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SessionSnapshot) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSnapshot) GetLastEventMs() uint32 {
	if x != nil {
		return x.LastEventMs
	}
	return 0
}

func (x *SessionSnapshot) GetWrittenAt() int64 {
	if x != nil {
		return x.WrittenAt
	}
	return 0
}

func (x *SessionSnapshot) GetFeatures() *FeatureState {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_events_v1_snapshot_proto protoreflect.FileDescriptor

var file_events_v1_snapshot_proto_rawDesc = []byte{
	0x0a, 0x18, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x67, 0x68, 0x6f, 0x73,
	0x74, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x1a, 0x1a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd0, 0x01, 0x0a,
	0x0f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x77, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x41, 0x74, 0x12,
	0x3e, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x42,
	0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46, 0x61,
	0x62, 0x69, 0x6f, 0x43, 0x61, 0x66, 0x66, 0x61, 0x72, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x67, 0x68,
	0x6f, 0x73, 0x74, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76,
	0x31, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_events_v1_snapshot_proto_rawDescOnce sync.Once
	file_events_v1_snapshot_proto_rawDescData = file_events_v1_snapshot_proto_rawDesc
)

func file_events_v1_snapshot_proto_rawDescGZIP() []byte {
	file_events_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_events_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_v1_snapshot_proto_rawDescData)
	})
	return file_events_v1_snapshot_proto_rawDescData
}

var file_events_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_v1_snapshot_proto_goTypes = []any{
	(*SessionSnapshot)(nil), // 0: ghosttrace.events.v1.SessionSnapshot
	(*FeatureState)(nil),    // 1: ghosttrace.events.v1.FeatureState
}
var file_events_v1_snapshot_proto_depIdxs = []int32{
	1, // 0: ghosttrace.events.v1.SessionSnapshot.features:type_name -> ghosttrace.events.v1.FeatureState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_v1_snapshot_proto_init() }
func file_events_v1_snapshot_proto_init() {
	if File_events_v1_snapshot_proto != nil {
		return
	}
	file_events_v1_evaluation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_v1_snapshot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_events_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_events_v1_snapshot_proto_msgTypes,
	}.Build()
	File_events_v1_snapshot_proto = out.File
	file_events_v1_snapshot_proto_rawDesc = nil
	file_events_v1_snapshot_proto_goTypes = nil
	file_events_v1_snapshot_proto_depIdxs = nil
}
