// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: events/v1/telemetry.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PointerPoint is one vertex of a decimated pointer polyline.
// Wire form is [x, y, dt] per docs/architecture.md §2; dt_ms is
// milliseconds since the previous point in the same polyline.
type PointerPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	DtMs          uint32                 `protobuf:"varint,3,opt,name=dt_ms,json=dtMs,proto3" json:"dt_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointerPoint) Reset() {
	*x = PointerPoint{}
	mi := &file_events_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointerPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointerPoint) ProtoMessage() {}

func (x *PointerPoint) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointerPoint.ProtoReflect.Descriptor instead.
func (*PointerPoint) Descriptor() ([]byte, []int) {
	return file_events_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *PointerPoint) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PointerPoint) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PointerPoint) GetDtMs() uint32 {
	if x != nil {
		return x.DtMs
	}
	return 0
}

// PointerEvent carries a decimated pointer polyline.
//
// Raw mousemove is several hundred events per second; the SDK decimates
// client-side and ships a polyline. M1 uses fixed-rate decimation at the
// server-driven collect.pointer_hz; the algorithm is a collect-policy
// field so it can change without an SDK release (contract §8.2).
type PointerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Milliseconds since session start. Never wall-clock — client
	// wall-clock is untrustworthy and leaks more than it gives (§2).
	TMs uint32 `protobuf:"varint,1,opt,name=t_ms,json=tMs,proto3" json:"t_ms,omitempty"`
	// "mouse" | "trackpad" | "touch" | "pen". A normalization property,
	// not an identifier: trackpad and mouse produce structurally
	// different traces and must not be compared without it (§0). The
	// shipping SDK emits pointerType verbatim — "touch", "pen", else
	// "mouse" — so "trackpad" is reserved vocabulary: browsers do not
	// expose it, and claiming it would require inference downstream.
	Src           string          `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Pts           []*PointerPoint `protobuf:"bytes,3,rep,name=pts,proto3" json:"pts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointerEvent) Reset() {
	*x = PointerEvent{}
	mi := &file_events_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointerEvent) ProtoMessage() {}

func (x *PointerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointerEvent.ProtoReflect.Descriptor instead.
func (*PointerEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *PointerEvent) GetTMs() uint32 {
	if x != nil {
		return x.TMs
	}
	return 0
}

func (x *PointerEvent) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *PointerEvent) GetPts() []*PointerPoint {
	if x != nil {
		return x.Pts
	}
	return nil
}

// TelemetryBatch is one accepted envelope from the browser (§2).
//
// Stored as an immutable observation. Everything in it arrived from a
// hostile source and is treated as a claim, not a fact (§1 trust model).
type TelemetryBatch struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Server-side session identifier. Deliberately NOT the session_token:
	// the token is a bearer credential with a 30-minute life, and the
	// archive outlives it. The token maps to this id server-side.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Per-session monotonic batch counter. Gaps are meaningful (§2).
	Seq uint32 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// Client-claimed milliseconds since session start.
	SentAtMs         uint32             `protobuf:"varint,4,opt,name=sent_at_ms,json=sentAtMs,proto3" json:"sent_at_ms,omitempty"`
	PagePath         string             `protobuf:"bytes,5,opt,name=page_path,json=pagePath,proto3" json:"page_path,omitempty"`
	ViewportW        uint32             `protobuf:"varint,6,opt,name=viewport_w,json=viewportW,proto3" json:"viewport_w,omitempty"`
	ViewportH        uint32             `protobuf:"varint,7,opt,name=viewport_h,json=viewportH,proto3" json:"viewport_h,omitempty"`
	PointerEvents    []*PointerEvent    `protobuf:"bytes,8,rep,name=pointer_events,json=pointerEvents,proto3" json:"pointer_events,omitempty"`
	KeyEvents        []*KeyEvent        `protobuf:"bytes,10,rep,name=key_events,json=keyEvents,proto3" json:"key_events,omitempty"`
	ScrollEvents     []*ScrollEvent     `protobuf:"bytes,11,rep,name=scroll_events,json=scrollEvents,proto3" json:"scroll_events,omitempty"`
	FocusEvents      []*FocusEvent      `protobuf:"bytes,12,rep,name=focus_events,json=focusEvents,proto3" json:"focus_events,omitempty"`
	VisibilityEvents []*VisibilityEvent `protobuf:"bytes,13,rep,name=visibility_events,json=visibilityEvents,proto3" json:"visibility_events,omitempty"`
	FormEvents       []*FormEvent       `protobuf:"bytes,14,rep,name=form_events,json=formEvents,proto3" json:"form_events,omitempty"`
	// Server wall-clock nanoseconds at acceptance. Server-observed, so
	// unlike every other timestamp here it is trustworthy — which is what
	// makes network-arrival-vs-claimed-time checks possible later (§1).
	ReceivedAt    int64 `protobuf:"varint,9,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_events_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_events_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryBatch) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TelemetryBatch) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TelemetryBatch) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TelemetryBatch) GetSentAtMs() uint32 {
	if x != nil {
		return x.SentAtMs
	}
	return 0
}

func (x *TelemetryBatch) GetPagePath() string {
	if x != nil {
		return x.PagePath
	}
	return ""
}

func (x *TelemetryBatch) GetViewportW() uint32 {
	if x != nil {
		return x.ViewportW
	}
	return 0
}

func (x *TelemetryBatch) GetViewportH() uint32 {
	if x != nil {
		return x.ViewportH
	}
	return 0
}

func (x *TelemetryBatch) GetPointerEvents() []*PointerEvent {
	if x != nil {
		return x.PointerEvents
	}
	return nil
}

func (x *TelemetryBatch) GetKeyEvents() []*KeyEvent {
	if x != nil {
		return x.KeyEvents
	}
	return nil
}

func (x *TelemetryBatch) GetScrollEvents() []*ScrollEvent {
	if x != nil {
		return x.ScrollEvents
	}
	return nil
}

func (x *TelemetryBatch) GetFocusEvents() []*FocusEvent {
	if x != nil {
		return x.FocusEvents
	}
	return nil
}

func (x *TelemetryBatch) GetVisibilityEvents() []*VisibilityEvent {
	if x != nil {
		return x.VisibilityEvents
	}
	return nil
}

func (x *TelemetryBatch) GetFormEvents() []*FormEvent {
	if x != nil {
		return x.FormEvents
	}
	return nil
}

func (x *TelemetryBatch) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

// KeyEvent carries key TIMING and coarse class, never content (§2, §6).
//
// The class taxonomy preserves cadence and digraph structure while
// making reconstruction of typed text infeasible: knowing that six
// alphas were typed at particular intervals says a great deal about
// whether a human typed them and nothing about what they were.
type KeyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	TMs   uint32                 `protobuf:"varint,1,opt,name=t_ms,json=tMs,proto3" json:"t_ms,omitempty"`
	// "down" | "up". Both are needed: dwell is down→up on one key and
	// flight is up→down between keys, and the two behave differently.
	Phase string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	// "alpha" | "digit" | "nav" | "mod" | "whitespace" | "other".
	KeyClass string `protobuf:"bytes,3,opt,name=key_class,json=keyClass,proto3" json:"key_class,omitempty"`
	// Stable hash of the field identity. Never its value.
	Target        string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEvent) Reset() {
	*x = KeyEvent{}
	mi := &file_events_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEvent) ProtoMessage() {}

func (x *KeyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEvent.ProtoReflect.Descriptor instead.
func (*KeyEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *KeyEvent) GetTMs() uint32 {
	if x != nil {
		return x.TMs
	}
	return 0
}

func (x *KeyEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *KeyEvent) GetKeyClass() string {
	if x != nil {
		return x.KeyClass
	}
	return ""
}

func (x *KeyEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// ScrollEvent carries scroll displacement and input mode.
type ScrollEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	TMs   uint32                 `protobuf:"varint,1,opt,name=t_ms,json=tMs,proto3" json:"t_ms,omitempty"`
	Dy    int32                  `protobuf:"varint,2,opt,name=dy,proto3" json:"dy,omitempty"`
	// "wheel" | "touch" | "key" | "programmatic". Programmatic scrolls
	// are a strong automation signal on their own — a person cannot
	// produce one. The shipping SDK emits only "wheel" and
	// "programmatic": it classifies by user-gesture presence, not input
	// device, so "touch" and "key" are reserved vocabulary until the
	// collector can tell them apart.
	Mode          string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrollEvent) Reset() {
	*x = ScrollEvent{}
	mi := &file_events_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrollEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollEvent) ProtoMessage() {}

func (x *ScrollEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollEvent.ProtoReflect.Descriptor instead.
func (*ScrollEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *ScrollEvent) GetTMs() uint32 {
	if x != nil {
		return x.TMs
	}
	return 0
}

func (x *ScrollEvent) GetDy() int32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

func (x *ScrollEvent) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// FocusEvent tracks focus and blur on identified fields.
//
// A form completed with no focus transitions at all was not completed
// by someone tabbing or clicking through it.
type FocusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TMs           uint32                 `protobuf:"varint,1,opt,name=t_ms,json=tMs,proto3" json:"t_ms,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "focus" | "blur"
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FocusEvent) Reset() {
	*x = FocusEvent{}
	mi := &file_events_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusEvent) ProtoMessage() {}

func (x *FocusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusEvent.ProtoReflect.Descriptor instead.
func (*FocusEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *FocusEvent) GetTMs() uint32 {
	if x != nil {
		return x.TMs
	}
	return 0
}

func (x *FocusEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *FocusEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// VisibilityEvent tracks page visibility.
type VisibilityEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TMs           uint32                 `protobuf:"varint,1,opt,name=t_ms,json=tMs,proto3" json:"t_ms,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "visible" | "hidden"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisibilityEvent) Reset() {
	*x = VisibilityEvent{}
	mi := &file_events_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityEvent) ProtoMessage() {}

func (x *VisibilityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityEvent.ProtoReflect.Descriptor instead.
func (*VisibilityEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *VisibilityEvent) GetTMs() uint32 {
	if x != nil {
		return x.TMs
	}
	return 0
}

func (x *VisibilityEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// FormEvent records how a field came to hold its value, against a
// field identity. Field identity only, never content.
type FormEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TMs    uint32                 `protobuf:"varint,1,opt,name=t_ms,json=tMs,proto3" json:"t_ms,omitempty"`
	Target string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// "paste" | "autofill" | "submit" | "injected".
	//
	// "injected" is the SDK's report that a field's value changed with no
	// preceding keydown on that field — page.fill, execute_script and
	// friends. It feeds FeatureState.injections, the policy's strongest
	// signal, so a client written from this schema that never emits it
	// produces sessions the best detector cannot see. This value was
	// live in the SDK before it was documented here; the enumeration in
	// this comment is the wire contract and must list every emitted
	// member. Known false-positive population: dictation, IME
	// composition, some assistive input (§6) — which is why the signal
	// is capped below categorical and cannot block alone.
	Action        string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormEvent) Reset() {
	*x = FormEvent{}
	mi := &file_events_v1_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormEvent) ProtoMessage() {}

func (x *FormEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormEvent.ProtoReflect.Descriptor instead.
func (*FormEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *FormEvent) GetTMs() uint32 {
	if x != nil {
		return x.TMs
	}
	return 0
}

func (x *FormEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *FormEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_events_v1_telemetry_proto protoreflect.FileDescriptor

var file_events_v1_telemetry_proto_rawDesc = []byte{
	0x0a, 0x19, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x67, 0x68, 0x6f,
	0x73, 0x74, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x22, 0x3f, 0x0a, 0x0c, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x13, 0x0a,
	0x05, 0x64, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x64, 0x74,
	0x4d, 0x73, 0x22, 0x69, 0x0a, 0x0c, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x11, 0x0a, 0x04, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x74, 0x4d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x34, 0x0a, 0x03, 0x70, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x03, 0x70, 0x74, 0x73, 0x22, 0xa5, 0x05,
	0x0a, 0x0e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x1c,
	0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x4d, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x65,
	0x77, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76,
	0x69, 0x65, 0x77, 0x70, 0x6f, 0x72, 0x74, 0x57, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x65, 0x77,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x69,
	0x65, 0x77, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x12, 0x49, 0x0a, 0x0e, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x0d, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x3d, 0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65,
	0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x46, 0x0a, 0x0d, 0x73, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x73, 0x63, 0x72,
	0x6f, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x43, 0x0a, 0x0c, 0x66, 0x6f, 0x63,
	0x75, 0x73, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x0b, 0x66, 0x6f, 0x63, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x52,
	0x0a, 0x11, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x68, 0x6f, 0x73,
	0x74, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x10, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x40, 0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x74,
	0x72, 0x61, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x6f, 0x72, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x66, 0x6f, 0x72, 0x6d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x41, 0x74, 0x22, 0x68, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x11, 0x0a, 0x04, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x74, 0x4d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65,
	0x79, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b,
	0x65, 0x79, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22,
	0x44, 0x0a, 0x0b, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x11,
	0x0a, 0x04, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x4d,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x64,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x4d, 0x0a, 0x0a, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x11, 0x0a, 0x04, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x74, 0x4d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x22, 0x3a, 0x0a, 0x0f, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x11, 0x0a, 0x04, 0x74, 0x5f, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x4d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x22, 0x4e, 0x0a, 0x09, 0x46, 0x6f, 0x72, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x11, 0x0a,
	0x04, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x4d, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46,
	0x61, 0x62, 0x69, 0x6f, 0x43, 0x61, 0x66, 0x66, 0x61, 0x72, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x67,
	0x68, 0x6f, 0x73, 0x74, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f,
	0x76, 0x31, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_events_v1_telemetry_proto_rawDescOnce sync.Once
	file_events_v1_telemetry_proto_rawDescData = file_events_v1_telemetry_proto_rawDesc
)

func file_events_v1_telemetry_proto_rawDescGZIP() []byte {
	file_events_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_events_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_v1_telemetry_proto_rawDescData)
	})
	return file_events_v1_telemetry_proto_rawDescData
}

var file_events_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_events_v1_telemetry_proto_goTypes = []any{
	(*PointerPoint)(nil),    // 0: ghosttrace.events.v1.PointerPoint
	(*PointerEvent)(nil),    // 1: ghosttrace.events.v1.PointerEvent
	(*TelemetryBatch)(nil),  // 2: ghosttrace.events.v1.TelemetryBatch
	(*KeyEvent)(nil),        // 3: ghosttrace.events.v1.KeyEvent
	(*ScrollEvent)(nil),     // 4: ghosttrace.events.v1.ScrollEvent
	(*FocusEvent)(nil),      // 5: ghosttrace.events.v1.FocusEvent
	(*VisibilityEvent)(nil), // 6: ghosttrace.events.v1.VisibilityEvent
	(*FormEvent)(nil),       // 7: ghosttrace.events.v1.FormEvent
}
var file_events_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: ghosttrace.events.v1.PointerEvent.pts:type_name -> ghosttrace.events.v1.PointerPoint
	1, // 1: ghosttrace.events.v1.TelemetryBatch.pointer_events:type_name -> ghosttrace.events.v1.PointerEvent
	3, // 2: ghosttrace.events.v1.TelemetryBatch.key_events:type_name -> ghosttrace.events.v1.KeyEvent
	4, // 3: ghosttrace.events.v1.TelemetryBatch.scroll_events:type_name -> ghosttrace.events.v1.ScrollEvent
	5, // 4: ghosttrace.events.v1.TelemetryBatch.focus_events:type_name -> ghosttrace.events.v1.FocusEvent
	6, // 5: ghosttrace.events.v1.TelemetryBatch.visibility_events:type_name -> ghosttrace.events.v1.VisibilityEvent
	7, // 6: ghosttrace.events.v1.TelemetryBatch.form_events:type_name -> ghosttrace.events.v1.FormEvent
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_events_v1_telemetry_proto_init() }
func file_events_v1_telemetry_proto_init() {
	if File_events_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_v1_telemetry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_events_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_events_v1_telemetry_proto_msgTypes,
	}.Build()
	File_events_v1_telemetry_proto = out.File
	file_events_v1_telemetry_proto_rawDesc = nil
	file_events_v1_telemetry_proto_goTypes = nil
	file_events_v1_telemetry_proto_depIdxs = nil
}
