#!/usr/bin/env bash
# Validate a commit message header against Conventional Commits v1.0.0.
#
# This exists so release automation can read the log. semantic-release
# derives the next version from the type: `feat` is a minor, `fix` and
# `perf` are patches, a `!` or a BREAKING CHANGE footer is a major, and
# everything else releases nothing. A header it cannot parse is a
# release it cannot cut.
#
# WHERE THIS ACTUALLY BITES. Pull requests here are squash-merged, so
# the commit that lands on main is the PULL REQUEST TITLE, not any of
# the commits written locally. The git hook is useful discipline; the
# CI check on the PR title is the one that determines what gets
# released. Both call this script, so there is one definition of the
# rule rather than two that drift.
#
# Usage:
#   check-commit-message.sh --file .git/COMMIT_EDITMSG
#   check-commit-message.sh --text "feat(api): add the thing"
#   check-commit-message.sh --selftest

set -euo pipefail

# The Angular set, which is what semantic-release's default commit
# analyser understands. Adding a type here without teaching the release
# config about it means commits that silently never release.
TYPES='feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert'

# scope is optional and free-form, but lowercase: this repository uses
# the milestone (`feat(r1.14): ...`) so `git log --oneline` stays
# greppable by milestone the way it has been since R0.1.
HEADER_RE="^(${TYPES})(\([a-z0-9][a-z0-9._/-]*\))?(!)?: .+"

MAX_HEADER=100

# Merges and the autosquash markers are generated by git itself and are
# never what gets released.
EXEMPT_RE='^(Merge |Revert |fixup! |squash! |amend! )'

fail() {
    local header="$1" reason="$2"
    cat >&2 <<EOF

  commit message rejected: ${reason}

    ${header}

  Expected Conventional Commits:  <type>[(scope)][!]: <description>

    type      ${TYPES//|/, }
    scope     optional, lowercase — this repo uses the milestone, e.g. (r1.14)
    !         marks a breaking change (also: a BREAKING CHANGE: footer)

  Examples:

    feat(r1.14): expose the decision contract as OpenAPI 3.1
    fix(policy): stop rounding scores below zero to positive
    ci(r1.13): pin every action by commit SHA
    refactor(session)!: ports take a context

  Releases: feat -> minor, fix|perf -> patch, ! -> major, others none.
  To bypass once (it will still be checked on the PR title): --no-verify

EOF
    return 1
}

# Extract the header: first line that is neither blank nor a git comment.
header_from_file() {
    local file="$1"
    grep -v '^#' -- "$file" | grep -m1 -v '^[[:space:]]*$' || true
}

check() {
    local header="$1"

    if [ -z "${header// /}" ]; then
        fail "(empty)" "the message is empty"
        return 1
    fi

    if [[ $header =~ $EXEMPT_RE ]]; then
        return 0
    fi

    if [ "${#header}" -gt "$MAX_HEADER" ]; then
        fail "$header" "header is ${#header} characters, limit is ${MAX_HEADER}"
        return 1
    fi

    if ! [[ $header =~ $HEADER_RE ]]; then
        fail "$header" "does not match <type>[(scope)][!]: <description>"
        return 1
    fi

    if [[ $header =~ \.$ ]]; then
        fail "$header" "description must not end with a period"
        return 1
    fi

    return 0
}

# --- selftest --------------------------------------------------------
#
# The rule is a regular expression, which is exactly the kind of thing
# that looks right and accepts the wrong set. These cases are the
# specification; `make ci` runs them.

selftest() {
    local -a valid=(
        'feat: add a thing'
        'feat(r1.14): expose the decision contract as OpenAPI 3.1'
        'fix(policy): stop rounding scores below zero'
        'refactor(session)!: ports take a context'
        'ci(r1.13): pin every action by commit SHA'
        'chore(deps): bump golang.org/x/sys from 0.22.0 to 0.23.0'
        'docs: describe the six numbers'
        'perf(feature): halve the allocation in the pointer path'
        'revert: feat(api) add the thing'
        'build(docker): move to distroless static'
        'Merge pull request #280 from FabioCaffarello/claude/r113-ci-cd'
        'Revert "feat: add a thing"'
        'fixup! feat: add a thing'
    )
    local -a invalid=(
        ''
        'R1.13: the quality gate becomes real'
        'added a thing'
        'feat add a thing'
        'feat:'
        'feat: '
        'Feat: add a thing'
        'feature: add a thing'
        'deps: bump something'
        'feat(R1.14): uppercase scope'
        'feat: add a thing.'
        'wip'
    )
    # A header at exactly the limit passes; one character more does not.
    valid+=("feat: $(printf 'a%.0s' $(seq 1 94))")
    invalid+=("feat: $(printf 'a%.0s' $(seq 1 95))")

    local failures=0 m
    for m in "${valid[@]}"; do
        if ! check "$m" 2>/dev/null; then
            echo "  FAIL  should be VALID:   ${m:0:72}"
            failures=$((failures + 1))
        fi
    done
    for m in "${invalid[@]}"; do
        if check "$m" 2>/dev/null; then
            echo "  FAIL  should be INVALID: ${m:0:72}"
            failures=$((failures + 1))
        fi
    done

    local total=$(( ${#valid[@]} + ${#invalid[@]} ))
    if [ "$failures" -ne 0 ]; then
        echo "  ${failures} of ${total} commit-message cases wrong"
        return 1
    fi
    echo "  ${total}/${total} commit-message cases hold"
    return 0
}

main() {
    case "${1:---help}" in
        --file)
            [ $# -ge 2 ] || { echo "usage: $0 --file <path>" >&2; exit 2; }
            check "$(header_from_file "$2")"
            ;;
        --text)
            [ $# -ge 2 ] || { echo "usage: $0 --text <message>" >&2; exit 2; }
            check "$2"
            ;;
        --selftest)
            selftest
            ;;
        *)
            sed -n '2,20p' "$0"
            exit 2
            ;;
    esac
}

main "$@"
